/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlockCode: typeof import('./src/components/BlockCode.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Card: typeof import('./src/components/ui/card/Card.vue')['default']
    CardAction: typeof import('./src/components/ui/card/CardAction.vue')['default']
    CardContent: typeof import('./src/components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./src/components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./src/components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./src/components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./src/components/ui/card/CardTitle.vue')['default']
    DataTable: typeof import('./src/components/ui/datatable/DataTable.vue')['default']
    Dialog: typeof import('./src/components/ui/dialog/Dialog.vue')['default']
    DialogClose: typeof import('./src/components/ui/dialog/DialogClose.vue')['default']
    DialogContent: typeof import('./src/components/ui/dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./src/components/ui/dialog/DialogDescription.vue')['default']
    DialogFooter: typeof import('./src/components/ui/dialog/DialogFooter.vue')['default']
    DialogHeader: typeof import('./src/components/ui/dialog/DialogHeader.vue')['default']
    DialogOverlay: typeof import('./src/components/ui/dialog/DialogOverlay.vue')['default']
    DialogScrollContent: typeof import('./src/components/ui/dialog/DialogScrollContent.vue')['default']
    DialogTitle: typeof import('./src/components/ui/dialog/DialogTitle.vue')['default']
    DialogTrigger: typeof import('./src/components/ui/dialog/DialogTrigger.vue')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    Map: typeof import('./src/components/ui/map/Map.vue')['default']
    ModalView: typeof import('./src/components/modals/ModalView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sonner: typeof import('./src/components/ui/sonner/Sonner.vue')['default']
  }
}
